#!/usr/bin/env sh
xinput set-prop "Logitech Wireless Mouse" "libinput Accel Speed" "-1"
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" "1"
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled Default" "0"
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Drag Enabled" "1"
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Drag Enabled Default" "1"
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Drag Lock Enabled" "0"
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Drag Lock Enabled Default" "0"
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Button Mapping Enabled" "1, 0"
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Button Mapping Default" "1, 0"
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" "1"
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled Default" "0"
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Disable While Typing Enabled" "1"
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Disable While Typing Enabled Default" "1"
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Scroll Methods Available" "1, 1, 0"
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Scroll Method Enabled" "1, 0, 0"
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Scroll Method Enabled Default" "1, 0, 0"
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Accel Speed" "0.000000"
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Accel Speed Default" "0.000000"
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Accel Profiles Available" "1, 1"
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Accel Profile Enabled" "1, 0"
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Accel Profile Enabled Default" "1, 0"
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Left Handed Enabled" "0"
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Left Handed Enabled Default" "0"
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Send Events Modes Available" "1, 1"
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Send Events Mode Enabled" "0, 0"
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Send Events Mode Enabled Default" "0, 0"
xinput set-prop "SynPS/2 Synaptics TouchPad" "Device Node" "'/dev/input/event13'"
xinput set-prop "SynPS/2 Synaptics TouchPad" "Device Product ID" "2, 7"
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Drag Lock Buttons" "<no items>"
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Horizontal Scroll Enabled" "1"
